# Test at a specific version in order to prevent accidentally requiring a new
# Rust version. Image tags are at: https://hub.docker.com/r/library/rust/tags/
image: "rust:1.30"

# If we run the test before the docs, we can cache the build and not waste time
# building it again.
stages:
  - test
  - doc

# Move a few of the "home" directories here so they are easier to cache.
variables:
  GIT_SUBMODULE_STRATEGY: normal
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

# Since we default to compiling nng, we need to install some C tooling.
before_script:
  - apt-get update -yqq
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -yqq --no-install-recommends build-essential cmake

# Use cargo to test the project
test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --all --verbose
  only:
    - tags
    - master
    - /^[0-9]+-.*$/


# Publish to the pages whenever master is updated
pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=nng">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master

# Store these before jobs to speed up the build
cache:
  paths:
    - apt/
    - cargo/
    - target/
