use_small_heuristics = "Max"
force_explicit_abi = true
hard_tabs = true
max_width = 100
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
edition = "2018"

indent_style = "Block"
binop_separator = "Front"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "ClosingNextLine"
disable_all_formatting = false
error_on_line_overflow = false
error_on_unformatted = false
fn_args_density = "Tall"
brace_style = "AlwaysNextLine"
empty_item_single_line = true
enum_discrim_align_threshold = 20
fn_single_line = true
where_single_line = false
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_imports = false
match_block_trailing_comma = true
force_multiline_blocks = false
normalize_comments = false
reorder_impl_items = true
report_todo = "Unnumbered"
report_fixme = "Unnumbered"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 20
spaces_around_ranges = false
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
format_doc_comments = true
wrap_comments = true
match_arm_blocks = true
overflow_delimited_expr = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
#required_version = "..."
hide_parse_errors = false
#color = "Auto"
unstable_features = true
#license_template_path = "..."
#ignore = [...]
version = "Two"
normalize_doc_attributes = true
